Submete Prefacio a revisao.
doverh/wstg-translations-pt pull request #5
Opened 2021-03-04 22:20 UTC by doverh

2023-11-09 13:53 UTC, niicao requested changes
Realizar a correção de alguns erros

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +Não é preciso dizer que você não pode criar um aplicativo seguro sem realizar testes de segurança nele. O teste é parte de uma abordagem mais ampla para construir sistemas seguros. Muitas organizaçõe
corrigir o "que n obedecer uma norma"

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +O teste de segurança, por si só, não é uma medida suficiente autônoma para determinar quão seguro um aplicativo é, porque há um número infinito de maneiras pelas quais um aplicativo pode ser invadido
retirar o "autônoma", já que o "por si só" reflete melhor a ideia de "stand alone" e não é necessário enfatizar duas vezes esta ideia

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +A importância de ter este guia disponível de forma totalmente gratuita e aberta é importante para a missão da fundação. Ele dá a qualquer pessoa a capacidade de compreender as técnicas usadas para te
"Deve ser aberta a todos e não exclusiva aos profissionais de segurança" pois refere-se a segurança

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +  <li>Especialistas em segurança devem usar este guia combinado com outras técnicas como uma forma de verificar se nenhuma falha de segurança foi       desconsiderada em um aplicativo.</li>
"usar este guia em conjunto com/aliado a outras técnicas..." é apenas uma sugestão, pois creio que transmita melhor a ideia

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +Inúmeras empresas vendem ferramentas automatizadas de análise e testes de segurança. Lembre-se das limitações dessas ferramentas e as use apenas naquilo em que são boas. Como Michael Howard colocou n
"e ajudam a firmar a aplicação de políticas", na ultima linha

2023-11-09 13:53 UTC, niicao commented on 0-Prefacio/README.md
> +Ainda mais importante, essas ferramentas são genéricas - o que significa que não foram projetadas especificamente para o seu código, mas para aplicativos em geral. Isso significa que, embora eles pos
"embora elas possam encontrar alguns problemas, elas não têm conhecimento suficiente do seu aplicativo"

2023-12-08 22:41 UTC, doverh commented
@niicao vou abandonar esse pull request. Como estava aberto há muito tempo, acabei modificando o processo de tradução segundo as orientações da OWASP. Inclui os passos no README file inicial. Basicamente, pode abrir um pull request para cada arquivo que revisar. Caso queira participar da tradução entre em contato.

2023-12-08 22:42 UTC, closed without merging